name: Trigger External Repository Dispatch

on:
  workflow_run:
    workflows: ["Version Update"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      wait_minutes:
        type: number
        description: "Minutes to wait before triggering (default: 10)"
        required: false
        default: 5

jobs:
  dispatch-to-admin:
    name: Notify Admin Repository
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    uses: iCloudHospital/iCloudHospital/.github/workflows/dispatch-trigger.yml@main
    with:
      target_repository: "iCloudHospital/cloudhospital.admin"
      event_type: "api-release-completed"
      package_name: "ch-chat-api-typescript-axios"
      wait_minutes: ${{ github.event.inputs.wait_minutes || 10 }}
      source_workflow: "Version Update"
      custom_payload: |
        {
          "deployment_environment": "production",
          "requires_manual_approval": false
        }